services:
  - type: web
    name: AgriVision-Fullstack
    env: docker
    plan: starter
    dockerfilePath: Dockerfile
    dockerContext: .
    branch: main
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: AGRI_MOCK_MODE
        value: "false"
    autoDeploy: true
    pullRequestPreviewsEnabled: true
